server:
  port: 8000

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql:///prometion?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    hikari:
      max-lifetime: 60000 # 一个连接的生命时长（毫秒）缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 30 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      minimum-idle: 10
      idle-timeout: 30000 # 连接允许在池中闲置的最长时间，默认为6000000， 即10分钟
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp